security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  role_hierarchy:
    ROLE_ADMIN: ROLE_USER
  providers:
    app_user_provider:
      entity:
        class: App\Entity\UserInfo
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      entry_point: App\Security\AuthenticationEntryPoint
      access_denied_handler: App\Security\AccessDeniedHandler
      lazy: true
      provider: app_user_provider
      json_login:
        check_path: /api/login
        success_handler: lexik_jwt_authentication.handler.authentication_success
        failure_handler: lexik_jwt_authentication.handler.authentication_failure
      form_login:
        login_path: login
        check_path: login
      logout:
        path: app_logout
      jwt: ~

  access_control:
    - { path: ^/api/login, roles: PUBLIC_ACCESS }
    - { path: ^/admin, roles: ROLE_ADMIN }
